import type { DigestSummary, SummaryItem } from "./summariser.js";

export function formatDigestHtml(summary: DigestSummary, date: string): string {
  const { needsReply, urgent, fyi } = summary;
  const totalCount = needsReply.length + urgent.length + fyi.length;

  const replyCards = needsReply.map((item) => `
    <div style="background:#fff8f0;border-left:4px solid #e8710a;border-radius:4px;padding:14px 16px;margin-bottom:12px;">
      <div style="font-size:13px;color:#888;margin-bottom:2px;">${escHtml(item.from)}</div>
      <div style="font-weight:600;font-size:15px;color:#111;margin-bottom:6px;">${escHtml(item.subject)}</div>
      <div style="font-size:14px;color:#333;margin-bottom:6px;">${escHtml(item.gist)}</div>
      ${item.asks ? `<div style="font-size:13px;color:#b45309;margin-bottom:6px;"><strong>They're asking:</strong> ${escHtml(item.asks)}</div>` : ""}
      ${item.suggestedAction ? `<div style="font-size:13px;color:#1a73e8;">→ <strong>Action:</strong> ${escHtml(item.suggestedAction)}</div>` : ""}
    </div>`).join("");

  const urgentRows = urgent.map((item) => `
    <tr>
      <td style="padding:8px 0;border-bottom:1px solid #f0f0f0;vertical-align:top;width:200px;">
        <strong style="color:#111;font-size:14px;">${escHtml(item.from)}</strong><br>
        <span style="color:#666;font-size:12px;">${escHtml(item.subject)}</span>
      </td>
      <td style="padding:8px 0 8px 16px;border-bottom:1px solid #f0f0f0;vertical-align:top;color:#333;font-size:14px;">
        ${escHtml(item.gist)}
      </td>
    </tr>`).join("");

  const fyiRows = fyi.map((item) => `
    <tr>
      <td style="padding:10px 0;border-bottom:1px solid #f0f0f0;vertical-align:top;width:200px;">
        <strong style="color:#111;font-size:14px;">${escHtml(item.from)}</strong><br>
        <span style="color:#666;font-size:12px;">${escHtml(item.subject)}</span>
      </td>
      <td style="padding:10px 0 10px 16px;border-bottom:1px solid #f0f0f0;vertical-align:top;font-size:14px;">
        <div style="color:#555;margin-bottom:${item.keyPoints?.length ? "6px" : "0"}">${escHtml(item.gist)}</div>
        ${item.keyPoints?.length ? `<ul style="margin:0;padding-left:18px;color:#333;">
          ${item.keyPoints.map((p) => `<li style="margin-bottom:2px;">${escHtml(p)}</li>`).join("")}
        </ul>` : ""}
      </td>
    </tr>`).join("");

  const sectionHeader = (emoji: string, title: string, count: number, color = "#1a73e8") =>
    `<h2 style="font-size:15px;color:#111;margin:28px 0 10px;border-left:3px solid ${color};padding-left:10px;">${emoji} ${title} <span style="color:#888;font-weight:normal;">(${count})</span></h2>`;

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:680px;margin:0 auto;padding:24px;color:#222;background:#fff;">
  <h1 style="font-size:20px;margin-bottom:2px;">Daily Digest</h1>
  <p style="color:#888;font-size:13px;margin-top:0 0 24px;">${escHtml(date)} &middot; ${totalCount} email${totalCount !== 1 ? "s" : ""}</p>

  ${needsReply.length ? `
  ${sectionHeader("💬", "Needs Your Reply", needsReply.length, "#e8710a")}
  ${replyCards}` : ""}

  ${urgent.length ? `
  ${sectionHeader("🔴", "Urgent / Important", urgent.length, "#dc2626")}
  <table style="width:100%;border-collapse:collapse;">${urgentRows}</table>` : ""}

  ${fyi.length ? `
  ${sectionHeader("📋", "FYI", fyi.length, "#6b7280")}
  <table style="width:100%;border-collapse:collapse;">${fyiRows}</table>` : ""}

  ${totalCount === 0 ? '<p style="color:#888;padding:16px 0;">Inbox zero — nothing to report.</p>' : ""}

  <hr style="margin-top:40px;border:none;border-top:1px solid #eee;">
  <p style="color:#bbb;font-size:12px;">Generated by your Chief of Staff agent.</p>
</body>
</html>`;
}

export function formatDigestPlainText(summary: DigestSummary, date: string): string {
  const lines: string[] = [`Daily Digest — ${date}`, ""];

  if (summary.needsReply.length) {
    lines.push(`== NEEDS YOUR REPLY (${summary.needsReply.length}) ==`);
    for (const item of summary.needsReply) {
      lines.push(`• ${item.from} | ${item.subject}`);
      lines.push(`  ${item.gist}`);
      if (item.asks) lines.push(`  They're asking: ${item.asks}`);
      if (item.suggestedAction) lines.push(`  → ${item.suggestedAction}`);
    }
    lines.push("");
  }

  if (summary.urgent.length) {
    lines.push(`== URGENT / IMPORTANT (${summary.urgent.length}) ==`);
    for (const item of summary.urgent) {
      lines.push(`• ${item.from} | ${item.subject}`);
      lines.push(`  ${item.gist}`);
    }
    lines.push("");
  }

  if (summary.fyi.length) {
    lines.push(`== FYI (${summary.fyi.length}) ==`);
    for (const item of summary.fyi) {
      lines.push(`• ${item.from} | ${item.subject}`);
      lines.push(`  ${item.gist}`);
      if (item.keyPoints?.length) {
        for (const pt of item.keyPoints) lines.push(`    - ${pt}`);
      }
    }
    lines.push("");
  }

  if (lines.length === 2) lines.push("Inbox zero — nothing to report.");

  return lines.join("\n");
}

function escHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
